language: node_js

node_js:
  - "lts/*"

cache:
  directories:
    - "node_modules"

script:
  - npm test

notifications:
  flowdock:
    secure: "p6xQI8bslQFLH9ho9QUAt27MQNvYzy2l75fXEDpTrsIK+nODJFBKrgvBPy/LzrCs7+aEOueabSLMeTQe5vkHRUhRLEDCpgvkXlSYzefkWA9K1nPPeJSbpn4Hkj58ntgfGCt7o9hGEuNi0zAMy4gmd5WITT6e+mNxFixy7QaDTjPzmIPVDs2rlyXYTLAF7uZAkdvw1TVY8OX5xf8iyTPVVr+D21uHNCqpsSlghvC2mFemgWchBbqXcCkd1bgOHr3Ev2+1YHqWm6Ee1jM0LSwmWhyZ/vq29WcZMCkMxrWrYqxIaIhB290iflz3lhYiaJU1szYCYcevmQRJ6AVryNkR9c+FGWfDtiBPVEGUZ9kbkhNk/xQwTNIPy1iuHiNyEPKfbeG3W1Kwei0O3HSeGIUX8f3i2S5IHZHOtYRExqXH6IAb7NeJXnZRWCW6jUGZtqIj1BYUAdfENM++6JhUultLz76ii41GL0vvZkRNZts4lg3JcxKxNHTExnLZvi8RzxGjyPkoAkkmCObSqaL/hVqLUWw577xBtRlniNMGa1qu9QjBQ/aiQlwbUNjone0pabHTJsnptJRHmmzmjq85kyj5bxGo/Aedrek+pnLUS7LS1+5saIflqaR2+1FDTsnaGXIkc/HYCQsl/WACi29ihgpHL9C8vrC1k5WoRXV7KLlr34I="
