language: node_js

node_js:
  - 'lts/*'

cache:
  directories:
    - '$HOME/.npm'

script:
  - npm test

notifications:
  flowdock:
    secure: 'oQfd5NgPVYEAfS8d6De/zwus7jttQRgwHSJI4xNXcYwLyxr8EwgkbvcwzNRneUKJrxav77dpkHE2eOZNTCMHzdWxqVlFCzA83KkYN17LrI4BoJ8ZGPFwDu2ktbXIsFAWyHsOgBE3m5Lfxesuh2/a/MuhLzg9o6kjbc6vDPZVNVy0C0S6oVfm6iUWviCS2V2VNxlieV5ljAnfFk8bl6fEtfygZuD6UnBq4eNKm3YtUeMYV01+u4UfDPxe1qggtfoX2OWe5A9QdgZdyptQ7zpbt/XaCM/VRTq0zDDA0Q/fapBFmWI8vVJQXkD0ZGY1gWaBn2Tm/P8V8GDm2B0CRLAfnke85YnkuSySdmcnmLNWUncdXRQXnjSFJARinD2bbYs/IWGeO9o1Ktrtr7fQQwSy66anATr3e2KKglUf3+aba/DhDGS8vMByi+iS2u95hDn/ojS7+t9HP9h94RFtPn2t+fGWIQyDtk/0DS886/p1MbX6vDLRop3xMw4VMhBKs39o5wIof7jSeXcrsZG13XjYAY6VSqJ4TjdGFzLi1AQs9qnjmIXjLBodvVZEp8F0W7ZxOcpn9EtQ+3qg8RTBgLyILpjhBDrrHTF+LOIGnbUKZxPSc683DjNTjfNFQckDWApli6UzjLViK3Z4W+s3bo6y6OdSXDLvXd3nu3GJiCJ85gM='
