export const FETCH_REGISTRY_CONTENT_START = 'FETCH_REGISTRY_CONTENT_START';
export const FETCH_REGISTRY_CONTENT_SUCCESS = 'FETCH_REGISTRY_CONTENT_SUCCESS';
export const FETCH_REGISTRY_CONTENT_FAIL = 'FETCH_REGISTRY_CONTENT_FAIL';

export const FETCH_ORGANIZATIONS_START = 'FETCH_ORGANIZATIONS_START';
export const FETCH_ORGANIZATIONS_SUCCESS = 'FETCH_ORGANIZATIONS_SUCCESS';
export const FETCH_ORGANIZATIONS_FAIL = 'FETCH_ORGANIZATIONS_FAIL';

export const ADD_REGISTRY_ITEM_START = 'ADD_REGISTRY_ITEM_START';
export const ADD_REGISTRY_ITEM_SUCCESS = 'ADD_REGISTRY_ITEM_SUCCESS';
export const ADD_REGISTRY_ITEM_FAIL = 'ADD_REGISTRY_ITEM_FAIL';

export const UPDATE_REGISTRY_ITEM_START = 'UPDATE_REGISTRY_ITEM_START';
export const UPDATE_REGISTRY_ITEM_SUCCESS = 'UPDATE_REGISTRY_ITEM_SUCCESS';
export const UPDATE_REGISTRY_ITEM_FAIL = 'UPDATE_REGISTRY_ITEM_FAIL';

export const DELETE_REGISTRY_ITEM_START = 'DELETE_REGISTRY_ITEM_START';
export const DELETE_REGISTRY_ITEM_SUCCESS = 'DELETE_REGISTRY_ITEM_SUCCESS';
export const DELETE_REGISTRY_ITEM_FAIL = 'DELETE_REGISTRY_ITEM_FAIL';

export const FETCH_EXAM_SESSION_CONTENT_START =
  'FETCH_EXAM_SESSION_CONTENT_START';
export const FETCH_EXAM_SESSION_CONTENT_SUCCESS =
  'FETCH_EXAM_SESSION_CONTENT_SUCCESS';
export const FETCH_EXAM_SESSION_CONTENT_FAIL =
  'FETCH_EXAM_SESSION_CONTENT_FAIL';

export const EXAM_SESSION_FAIL_RESET = 'EXAM_SESSION_FAIL_RESET';
export const REGISTRY_FAIL_RESET = 'REGISTRY_FAIL_RESET';
export const EXAM_DATES_FAIL_RESET = 'EXAM_DATES_FAIL_RESET';

export const ADD_EXAM_SESSION_START = 'ADD_EXAM_SESSION_START';
export const ADD_EXAM_SESSION_SUCCESS = 'ADD_EXAM_SESSION_SUCCESS';
export const ADD_EXAM_SESSION_FAIL = 'ADD_EXAM_SESSION_FAIL';

export const ADD_POST_ADMISSION_START = 'ADD_POST_ADMISSION_START';
export const ADD_POST_ADMISSION_SUCCESS = 'ADD_POST_ADMISSION_SUCCESS';
export const ADD_POST_ADMISSION_FAIL = 'ADD_POST_ADMISSION_FAIL';

export const FETCH_EXAM_SESSION_PARTICIPANTS_START =
  'FETCH_EXAM_SESSION_PARTICIPANTS_START';
export const FETCH_EXAM_SESSION_PARTICIPANTS_SUCCESS =
  'FETCH_EXAM_SESSION_PARTICIPANTS_SUCCESS';
export const FETCH_EXAM_SESSION_PARTICIPANTS_FAIL =
  'FETCH_EXAM_SESSION_PARTICIPANTS_FAIL';

export const UPDATE_EXAM_SESSION_START = 'UPDATE_EXAM_SESSION_START';
export const UPDATE_EXAM_SESSION_SUCCESS = 'UPDATE_EXAM_SESSION_SUCCESS';
export const UPDATE_EXAM_SESSION_FAIL = 'UPDATE_EXAM_SESSION_FAIL';

export const DELETE_EXAM_SESSION_START = 'DELETE_EXAM_SESSION_START';
export const DELETE_EXAM_SESSION_SUCCESS = 'DELETE_EXAM_SESSION_SUCCESS';
export const DELETE_EXAM_SESSION_FAIL = 'DELETE_EXAM_SESSION_FAIL';

export const EXAM_SESSION_CANCEL_REGISTRATION_START =
  'EXAM_SESSION_CANCEL_REGISTRATION_START';
export const EXAM_SESSION_CANCEL_REGISTRATION_SUCCESS =
  'EXAM_SESSION_CANCEL_REGISTRATION_SUCCESS';
export const EXAM_SESSION_CANCEL_REGISTRATION_FAIL =
  'EXAM_SESSION_CANCEL_REGISTRATION_FAIL';

export const EXAM_SESSION_CONFIRM_PAYMENT_START =
  'EXAM_SESSION_CONFIRM_PAYMENT_START';
export const EXAM_SESSION_CONFIRM_PAYMENT_SUCCESS =
  'EXAM_SESSION_CONFIRM_PAYMENT_SUCCESS';
export const EXAM_SESSION_CONFIRM_PAYMENT_FAIL =
  'EXAM_SESSION_CONFIRM_PAYMENT_FAIL';

export const EXAM_SESSION_RELOCATE_START = 'EXAM_SESSION_RELOCATE_START';
export const EXAM_SESSION_RELOCATE_SUCCESS = 'EXAM_SESSION_RELOCATE_SUCCESS';
export const EXAM_SESSION_RELOCATE_FAIL = 'EXAM_SESSION_RELOCATE_FAIL';

export const EXAM_SESSION_RESEND_EMAIL_START =
  'EXAM_SESSION_RESEND_EMAIL_START';
export const EXAM_SESSION_RESEND_EMAIL_SUCCESS =
  'EXAM_SESSION_RESEND_EMAIL_SUCCESS';
export const EXAM_SESSION_RESEND_EMAIL_FAIL = 'EXAM_SESSION_RESEND_EMAIL_FAIL';

export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';

export const FETCH_EXAM_DATES_START = 'FETCH_EXAM_DATES_START';
export const FETCH_EXAM_DATES_SUCCESS = 'FETCH_EXAM_DATES_SUCCESS';
export const FETCH_EXAM_DATES_FAIL = 'FETCH_EXAM_DATES_FAIL';

export const ADD_EXAM_DATE_START = 'ADD_EXAM_DATE_START';
export const ADD_EXAM_DATE_SUCCESS = 'ADD_EXAM_DATE__SUCCESS';
export const ADD_EXAM_DATE_FAIL = 'ADD_EXAM_DATE_FAIL';

export const CONFIGURE_EXAM_DATE_LANGUAGES_START =
  'CONFIGURE_EXAM_DATE_LANGUAGES_START';
export const CONFIGURE_EXAM_DATE_LANGUAGES_SUCCESS =
  'CONFIGURE_EXAM_DATE_LANGUAGES_SUCCESS';
export const CONFIGURE_EXAM_DATE_LANGUAGES_FAIL =
  'CONFIGURE_EXAM_DATE_LANGUAGES_FAIL';

export const CONFIGURE_EXAM_DATE_POST_ADMISSION_START =
  'CONFIGURE_EXAM_DATE_POST_ADMISSION_START';
export const CONFIGURE_EXAM_DATE_POST_ADMISSION_SUCCESS =
  'CONFIGURE_EXAM_DATE_POST_ADMISSION_SUCCESS';
export const CONFIGURE_EXAM_DATE_POST_ADMISSION_FAIL =
  'CONFIGURE_EXAM_DATE_POST_ADMISSION_FAIL';

export const DELETE_EXAM_DATE_START = 'DELETE_EXAM_DATE_START';
export const DELETE_EXAM_DATE_SUCCESS = 'DELETE_EXAM_DATE_SUCCESS';
export const DELETE_EXAM_DATE_FAIL = 'DELETE_EXAM_DATE_FAIL';

export const FETCH_EXAM_SESSIONS_START = 'FETCH_EXAM_SESSIONS_START';
export const FETCH_EXAM_SESSIONS_FAIL = 'FETCH_EXAM_SESSIONS_FAIL';
export const FETCH_EXAM_SESSIONS_SUCCESS = 'FETCH_EXAM_SESSIONS_SUCCESS';

export const TOGGLE_PAST_EXAM_SESSIONS = 'TOGGLE_PAST_EXAM_SESSIONS';
export const FETCH_REGISTRY_EXAM_SESSIONS_START =
  'FETCH_REGISTRY_EXAM_SESSIONS_START';
export const FETCH_REGISTRY_EXAM_SESSIONS_FAIL =
  'FETCH_REGISTRY_EXAM_SESSIONS_FAIL';
export const FETCH_REGISTRY_EXAM_SESSIONS_SUCCESS =
  'FETCH_REGISTRY_EXAM_SESSIONS_SUCCESS';

export const FETCH_REGISTRY_EXAM_SESSION_PARTICIPANTS_START =
  'FETCH_REGISTRY_EXAM_SESSION_PARTICIPANTS_START';
export const FETCH_REGISTRY_EXAM_SESSION_PARTICIPANTS_FAIL =
  'FETCH_REGISTRY_EXAM_SESSION_PARTICIPANTS_FAIL';
export const FETCH_REGISTRY_EXAM_SESSION_PARTICIPANTS_SUCCESS =
  'FETCH_REGISTRY_EXAM_SESSION_PARTICIPANTS_SUCCESS';

export const ADD_EXAM_LOCATIONS = 'ADD_EXAM_LOCATIONS';
export const FILTER_AND_GROUP_BY_DATE = 'FILTER_AND_GROUP_BY_DATE';
export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';
export const SELECT_LEVEL = 'SELECT_LEVEL';
export const SELECT_LOCATION = 'SELECT_LOCATION';
export const CHANGE_SESSION_SELECTOR = 'CHANGE_SESSION_SELECTOR';
export const FILTER_BY_OPEN_REGISTRATION = 'FILTER_BY_OPEN_REGISTRATION';
export const FILTER_BY_AVAILABILITY = 'FILTER_BY_AVAILABILITY';
export const FILTER_BY_AVAILABILITY_AND_REGISTRATION =
  'FILTER_BY_AVAILABILITY_AND_REGISTRATION';
export const TOGGLE_AVAILABILITY_FILTER = 'TOGGLE_AVAILABILITY_FILTER';
export const TOGGLE_OPEN_REGISTRATION_FILTER =
  'TOGGLE_OPEN_REGISTRATION_FILTER';

export const SELECT_EXAM_SESSION = 'SELECT_EXAM_SESSION';
export const FETCH_EXAM_SESSION_START = 'FETCH_EXAM_SESSION_START';
export const FETCH_EXAM_SESSION_SUCCESS = 'FETCH_EXAM_SESSION_SUCCESS';
export const FETCH_EXAM_SESSION_FAIL = 'FETCH_EXAM_SESSION_FAIL';

export const INIT_REGISTRATION_FORM_START = 'INIT_REGISTRATION_FORM_START';
export const INIT_REGISTRATION_FORM_FAIL = 'INIT_REGISTRATION_FORM_FAIL';
export const INIT_REGISTRATION_FORM_SUCCESS = 'INIT_REGISTRATION_FORM_SUCCESS';

export const SUBMIT_REGISTRATION_FORM_START = 'SUBMIT_REGISTRATION_FORM_START';
export const SUBMIT_REGISTRATION_FORM_FAIL = 'SUBMIT_REGISTRATION_FORM_FAIL';
export const SUBMIT_REGISTRATION_FORM_SUCCESS =
  'SUBMIT_REGISTRATION_FORM_SUCCESS';

export const INIT_YKI_LANGUAGE = 'INIT_YKI_LANGUAGE';
export const CHANGE_YKI_LANGUAGE = 'CHANGE_YKI_LANGUAGE';

export const FETCH_PRICES_START = 'FETCH_PRICES_START';
export const FETCH_PRICES_SUCCESS = 'FETCH_PRICES_SUCCESS';
export const FETCH_PRICES_FAIL = 'FETCH_PRICES_FAIL';

export const FETCH_REEVALUATION_PERIODS_START =
  'FETCH_REEVALUATION_PERIODS_START';
export const FETCH_REEVALUATION_PERIODS_SUCCESS =
  'FETCH_REEVALUATION_PERIODS_SUCCESS';
export const FETCH_REEVALUATION_PERIODS_FAIL =
  'FETCH_REEVALUATION_PERIODS_FAIL';

export const FETCH_REEVALUATION_PERIOD_START =
  'FETCH_REEVALUATION_PERIOD_START';
export const FETCH_REEVALUATION_PERIOD_SUCCESS =
  'FETCH_REEVALUATION_PERIOD_SUCCESS';
export const FETCH_REEVALUATION_PERIOD_FAIL = 'FETCH_REEVALUATION_PERIOD_FAIL';

export const SUBMIT_EVALUATION_FORM_START = 'SUBMIT_EVALUATION_FORM_START';
export const SUBMIT_EVALUATION_FORM_SUCCESS = 'SUBMIT_EVALUATION_FORM_SUCCESS';
export const SUBMIT_EVALUATION_FORM_FAIL = 'SUBMIT_EVALUATION_FORM_FAIL';
export const SUBMIT_EVALUATION_FORM_FAIL_RESET =
  'SUBMIT_EVALUATION_FORM_FAIL_RESET';

export const ADD_EVALUATION_PERIOD_START = 'ADD_EVALUATION_PERIOD_START';
export const ADD_EVALUATION_PERIOD_SUCCESS = 'ADD_EVALUATION_PERIOD_SUCCESS';
export const ADD_EVALUATION_PERIOD_FAIL = 'ADD_EVALUATION_PERIOD_FAIL';
export const SET_WINDOW_WIDTH = 'SET_WINDOW_WIDTH ';

export const FETCH_PAYMENTS_REPORT_START = 'FETCH_PAYMENTS_REPORT_START';
export const FETCH_PAYMENTS_REPORT_SUCCESS = 'FETCH_PAYMENTS_REPORT_SUCCESS';
export const FETCH_PAYMENTS_REPORT_FAIL = 'FETCH_PAYMENTS_REPORT_FAIL';
export const FETCH_PAYMENTS_REPORT_RESET = 'FETCH_PAYMENTS_REPORT_RESET';
