name: YKI-frontend

on:
  workflow_dispatch:
  push:
    paths:
      - "**"
      - "!**/*.md"
    # Setting 'branches' has the side effect that just pushing tags does not start workflows.
    branches:
      - '**'

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          # Note: does not cache node_modules
          # Use instead actions/cache explicitly if caching node_modules is desired
          cache: 'npm'
          cache-dependency-path: src/main/js/

      - name: Install NPM dependencies
        run: npm ci --prefix src/main/js/

      - name: Run tests
        run: npm test --prefix src/main/js/

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package

      - uses: actions/cache@v3
        id: restore-build
        with:
          path: target
          key: ${{ github.sha }}

  deploy:
    needs: [build]
    uses: Opetushallitus/.github/.github/workflows/push-scan-java-ecr.yml@main
    with:
      application: yki-frontend
      base-image: baseimage-fatjar-openjdk17:master
      configfolder: src/main/resources
      jarfile: yki-frontend.jar
      jarfolder: target
    secrets:
      AWS_UTILITY_ROLE_ARN: ${{ secrets.AWS_OPH_UTILITY_ROLE_ARN }}
